on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment you want to rollback'
        required: true
        default: 'production'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/get-last-successful-deployment
      id: last-successful-deployment
      with:
        environment: ${{ github.event.inputs.environment }}
    - run: |
        echo ${{ steps.last-successful-deployment.outputs.deployment-sha}}
        echo ${{ fromJSON(steps.last-successful-deployment.outputs.deployment) }}